### ISSUE TITLE
V12 compatability

### ISSUE THREAD

**Issue by belkasro** [miki4920/foundryvtt-pf2e-monster-maker#17]
any ETA on V12 compatability or the remaster threw you for a loop to get the V12 done

**Comment by mikolajg-tt** [comment]
Hi, the PF2E system is still in beta. I will look into V12 compatibility once the system goes out of beta.

**Comment by Arthil11** [comment]
Live now, it seems! Hopefully it's just a matter of changing a number.

**Comment by mikolajg-tt** [comment]
Updated to version 12. I will slowly start working on other features now.
