### ISSUE TITLE
Attribute `id` is missing in `module.json` 

### ISSUE THREAD

**Issue by rikmarais** [miki4920/foundryvtt-pf2e-monster-maker#6]
Hey there 👋 

I noticed that the `id` attribute is missing in the manifest file, and was hoping that I might ask you to add it and also to bump the version number of the release.

I think that there might have been a release of `1.2` and a change to the release soon after to add v11 compatibility fields without the version having being bumped, as the Forge's Bazaar still has the previous compatibility fields.

**Comment by mikolajg-tt** [comment]
Sorted. In terms of version, the version should be updated automatically in each release. 
The module.json in the main github repository should not be used, instead please use the following link:

 https://github.com/miki4920/foundryvtt-pf2e-monster-maker/releases/latest/download/module.json
