### ISSUE TITLE
Support for Abysmal Level stats

### ISSUE THREAD

**Issue by Peach774** [miki4920/foundryvtt-pf2e-monster-maker#9]
Abysmal isnt supported and is supposed to be an option for a stat worse than terrible. Please add support for this.

**Comment by mikolajg-tt** [comment]
Hi Peach,

I can incorporate it for ability score modifiers since they have predefined values. However, if you'd like me to include it for other statistics (Like Saves or AC), please provide a source I can refer to for those values.

**Comment by Peach774** [comment]
> 

https://monster.pf2.tools/ I was using this, which has abysmal ability scores and terrible skill stats which are also missing

**Comment by mikolajg-tt** [comment]
Sorted. Both should be available in the newest update. Just update it on foundry.
